# Generated by Django 3.2 on 2023-02-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=128, verbose_name='Вид животного')),
                ('description', models.TextField(verbose_name='Описание животного')),
                ('birthday', models.DateField(verbose_name='День рождения животного')),
                ('image', models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Фотография животного')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
    ]
